<!DOCTYPE html>
<html>
<head>
    <title>
        Vacation Solution - Management System
    </title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        main {
            flex: 1;
            display: flex;
            justify-content: center;
            flex-direction: column;
            align-items: center;
            padding: 20px;
        }

        footer {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 10px;
            margin-top: auto;
        }
        div {
            width: 600px;
            margin: 0 auto;
            padding: 60px;
        }
        a {
            display: block;
        }
    </style>
</head>
<body>
<main>
    <a href="/vacation-requests">Запросы...</a>
    <hr>
    <a href="/login">Войти</a>
    <hr>
    <a href="/registration">Зарегистрироваться</a>
</main>
<div>
    <script type="text/javascript" charset="utf-8" async
            src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Ad3c3dc6609dbd6b2a02ab4b0a304a85b6e592f1a939d450419478d19bcd48747&amp;width=600&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>

</div>
</body>
<footer>
    &copy; 2024 Vacation Solution
</footer>
</html>